version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pars_hh
      MYSQL_USER: user
      MYSQL_PASSWORD: 54162004Mmarat!
    ports:
      - "3307:3306"  # Changed host port to 3307
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=8080
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
